version: "3.8"
networks:
    laravel:
        driver: bridge
services:
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            - app
            - db
    db:
        image: postgres
        container_name: postgres
        # volumes:
        #     - postgresql-data
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: laravel_based
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: abcd1234@@
        networks:
            - laravel
    app:
        container_name: laravel_based
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./src/:/var/www
        ports:
            - "9000:9000"
        working_dir: "/var/www"
        networks:
            - laravel
