version: "3.8"
services:
    app:
        container_name: laravel_based
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./src/:/var/www
        ports:
            - "9000:9000"
        working_dir: "/var/www"
        networks:
            - laravel
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            - app
            - db
    db:
        image: postgres
        container_name: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgconf:/etc/postgresql
            - pglog:/var/log/postgresql
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_DB=laravel_based
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=abcd1234@@
        networks:
            - laravel
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        tty: true
        ports:
            - "6379:6379"
        networks:
            - laravel
    # frontend:
    #     container_name: frontend_app
    #     build:
    #         context: .
    #         dockerfile: ./docker/app/Dockerfile
    #     ports:
    #         - 2807:2807
    #     networks:
    #         - laravel
    mail_catcher:
        image: dockage/mailcatcher:0.7.1
        container_name: mailcatcher
        restart: on-failure:10
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
            - laravel
    minio:
        image: minio/minio:latest
        restart: always
        command:
            - server
            - --console-address
            - :9001
            - /data
        ports:
            - 9001:9001
        networks:
            - laravel
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniostorage}
            MINIO_REGION_NAME: ${MINIO_REGION_NAME:-us-east-1}
        volumes:
            - ${PATH_DATA:-./data}/minio:/data
networks:
    laravel:
        driver: bridge
volumes:
    pgdata:
        driver: local
    pgconf:
        driver: local
    pglog:
        driver: local
